### PR TITLE
Basic widgets

### PR DESCRIPTION
**Pull request by Scaler358**
Hard work with Oleg Andrus of adding primitive widgets has ended. Please praise the result of our work.

### CODE REVIEW

**Comment by OlegAndrus12** [comment]
Not the best one!
But still work as well.
Ready to merge

**Comment by OlegAndrus12** [comment]
Need to add button Registration to Log in navbar

**Comment by Scaler358** [comment]
> I don't think this is good implementation of register part. It should be calmer, maybe update design for log in and sign up.

Could you please add more details? Give us explanation of "calm design" and point what should be updated

**Comment by RomanLevkovych** [comment]
> > I don't think this is good implementation of register part. It should be calmer, maybe update design for log in and sign up.
> 
> Could you please add more details? Give us explanation of "calm design" and point what should be updated

Current version of log in part with sign in don't suit to general view of log in. I would prefer just one more button to navbar. Let this place will be empty. We can add image there or something else.

**Comment by Scaler358** [comment]
> > > I don't think this is good implementation of register part. It should be calmer, maybe update design for log in and sign up.
> > 
> > 
> > Could you please add more details? Give us explanation of "calm design" and point what should be updated
> 
> Current version of log in part with sign in don't suit to general view of log in. I would prefer just one more button to navbar. Let this place will be empty. We can add image there or something else.

Please review calmer version of register

**Comment by OlegAndrus12** [comment]
I think it is calm enough.
We should merge to development these widgets

**Pull request merged**
